version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-northeast-2"
    AWS_ACCOUNT_ID: "ed"
    REPOSITORY_URI: "public.ecr.aws/z8v3e5w8/asacecr"
    IMAGE_TAG: "tag"

phases:
  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

